#!/usr/bin/env python3
"""
GitHub Formatter for aibomstd
Converts AIBOM scan results to GitHub PR comment markdown
"""

import json
import argparse
from pathlib import Path
from typing import Dict, Any, Optional


class GitHubFormatter:
    """Formats AIBOM results as GitHub PR comment"""
    
    def __init__(self, aibom_path: str, violations_path: Optional[str] = None):
        self.aibom_path = Path(aibom_path)
        self.violations_path = Path(violations_path) if violations_path else None
        
        self.aibom = self._load_json(self.aibom_path)
        self.violations = self._load_json(self.violations_path) if self.violations_path else {}
    
    def _load_json(self, path: Path) -> Dict[str, Any]:
        """Load JSON file"""
        if not path or not path.exists():
            return {}
        
        try:
            with open(path) as f:
                return json.load(f)
        except json.JSONDecodeError:
            return {}
    
    def format_comment(self, risk_score: int = 0, violations_count: int = 0) -> str:
        """Format results as GitHub PR comment markdown"""
        
        # Status emoji and color
        if violations_count == 0:
            status_emoji = '✅'
            status_text = 'All checks passed'
            color = 'green'
        elif violations_count <= 3:
            status_emoji = '⚠️'
            status_text = 'Issues detected'
            color = 'yellow'
        else:
            status_emoji = '❌'
            status_text = 'Multiple issues found'
            color = 'red'
        
        # Build comment
        comment = f"""## {status_emoji} aibomstd Security Scan Results

**Status:** {status_text} | **Risk Score:** {risk_score}/100

### 📋 Scan Summary

| Metric | Value |
|--------|-------|
| Models | {self._count_components('models')} |
| Datasets | {self._count_components('datasets')} |
| Frameworks | {self._count_components('frameworks')} |
| External APIs | {self._count_components('api-clients')} |
| **Policy Violations** | **{violations_count}** |
| **Risk Score** | **{risk_score}/100** |

"""
        
        # Add violations section
        if violations_count > 0:
            comment += self._format_violations()
        else:
            comment += "### ✅ All Policies Passed\n\n"
        
        # Add component details
        comment += self._format_components()
        
        # Add footer
        comment += f"""

---

<details>
<summary>📊 View AIBOM Details</summary>

**Scan Metadata:**
- Timestamp: {self.aibom.get('metadata', {}).get('scan_time', 'N/A')}
- aibomstd Version: {self.aibom.get('metadata', {}).get('aibomstd_version', 'N/A')}
- Spec Version: {self.aibom.get('spec_version', 'N/A')}

**Data Residency Declarations:**
"""
        
        apis = self.aibom.get('components', {}).get('api-clients', [])
        for api in apis:
            residency = api.get('data-residency-declared', 'Not declared')
            comment += f"- {api.get('name')}: {residency}\n"
        
        comment += """
</details>

---

**Legend:**
- 🟢 **Low Risk** (0-25): No or minimal issues
- 🟡 **Medium Risk** (26-50): Some issues, review recommended
- 🔴 **High Risk** (51-75): Critical issues, fix required
- ⚫ **Critical** (76-100): Severe vulnerabilities, immediate action needed

*Generated by [aibomstd](https://github.com/aibomstd/aibomstd)*
"""
        
        return comment
    
    def _count_components(self, component_type: str) -> int:
        """Count components by type"""
        components = self.aibom.get('components', {})
        return len(components.get(component_type, []))
    
    def _format_violations(self) -> str:
        """Format violations section"""
        violations = self.violations.get('violations', [])
        
        if not violations:
            return ""
        
        comment = f"### ⚠️ Policy Violations ({len(violations)})\n\n"
        
        for i, v in enumerate(violations, 1):
            severity = v.get('severity', 'medium').upper()
            severity_emoji = self._severity_emoji(severity)
            
            comment += f"{i}. {severity_emoji} **{severity}** - {v.get('message', 'Unknown issue')}\n"
            comment += f"   - Component: `{v.get('component', 'unknown')}`\n\n"
        
        comment += "**Recommended Actions:**\n"
        comment += "- Review and fix violations before merging\n"
        comment += "- Update model origins and data residency declarations\n"
        comment += "- Consider upgrading vulnerable dependencies\n\n"
        
        return comment
    
    def _severity_emoji(self, severity: str) -> str:
        """Map severity to emoji"""
        severity_lower = severity.lower()
        if severity_lower == 'critical':
            return '🔴'
        elif severity_lower == 'high':
            return '🟠'
        elif severity_lower == 'medium':
            return '🟡'
        else:
            return '🟢'
    
    def _format_components(self) -> str:
        """Format component details"""
        components = self.aibom.get('components', {})
        
        comment = "### 📦 Components Detected\n\n"
        
        # Models
        models = components.get('models', [])
        if models:
            comment += "**Models:**\n"
            for model in models[:5]:  # Limit to 5 in comment
                source = model.get('origin', 'unknown')
                comment += f"- `{model.get('name')}` (origin: {source})\n"
            if len(models) > 5:
                comment += f"- ... and {len(models) - 5} more\n"
            comment += "\n"
        
        # Datasets
        datasets = components.get('datasets', [])
        if datasets:
            comment += "**Datasets:**\n"
            for ds in datasets[:3]:  # Limit to 3
                comment += f"- `{ds.get('name')}` ({ds.get('size', 'unknown')} records)\n"
            if len(datasets) > 3:
                comment += f"- ... and {len(datasets) - 3} more\n"
            comment += "\n"
        
        # External APIs
        apis = [a for a in components.get('api-clients', []) if a.get('type') == 'external']
        if apis:
            comment += "**External APIs:**\n"
            for api in apis:
                residency = api.get('data-residency-declared', '❌ Not declared')
                residency_emoji = '✅' if api.get('data-residency-declared') else '❌'
                comment += f"- {residency_emoji} `{api.get('name')}` ({residency})\n"
            comment += "\n"
        
        # Frameworks
        frameworks = components.get('frameworks', [])
        if frameworks:
            comment += "**ML Frameworks:**\n"
            for fw in frameworks:
                comment += f"- `{fw.get('name')}` v{fw.get('version', 'unknown')}\n"
            comment += "\n"
        
        return comment


def main():
    parser = argparse.ArgumentParser(
        description='Format AIBOM results as GitHub PR comment'
    )
    parser.add_argument('--aibom', required=True, help='Path to AIBOM JSON')
    parser.add_argument('--violations', help='Path to violations JSON')
    parser.add_argument('--output-comment', help='Output comment markdown to file')
    parser.add_argument('--risk-score', type=int, default=0, help='Risk score 0-100')
    parser.add_argument('--violations-count', type=int, default=0, help='Number of violations')
    
    args = parser.parse_args()
    
    # Format comment
    formatter = GitHubFormatter(args.aibom, args.violations)
    comment = formatter.format_comment(args.risk_score, args.violations_count)
    
    # Output to file if requested
    if args.output_comment:
        output_path = Path(args.output_comment)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(comment)
        
        print(f"✅ Comment written to {output_path}")
    else:
        print(comment)


if __name__ == '__main__':
    main()
