import json
from datetime import datetime


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>aibomstd Report — {subject_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f5; margin: 0; padding: 20px; color: #1a1a1a; }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  .header {{ background: #1a1a1a; color: white; padding: 24px 32px; border-radius: 8px; margin-bottom: 20px; }}
  .header h1 {{ margin: 0 0 4px 0; font-size: 24px; }}
  .header p {{ margin: 0; color: #aaa; font-size: 13px; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 20px; }}
  .stat {{ background: white; padding: 16px; border-radius: 8px; border: 1px solid #e0e0e0; }}
  .stat .label {{ font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }}
  .stat .value {{ font-size: 24px; font-weight: 700; }}
  .risk-none {{ color: #15803d; }}
  .risk-low {{ color: #65a30d; }}
  .risk-medium {{ color: #d97706; }}
  .risk-high {{ color: #dc2626; }}
  .risk-critical {{ color: #7c3aed; }}
  .section {{ background: white; border-radius: 8px; border: 1px solid #e0e0e0; margin-bottom: 16px; overflow: hidden; }}
  .section-header {{ padding: 14px 20px; background: #f8f8f8; border-bottom: 1px solid #e0e0e0; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; color: #444; }}
  .component {{ padding: 16px 20px; border-bottom: 1px solid #f0f0f0; }}
  .component:last-child {{ border-bottom: none; }}
  .component-header {{ display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }}
  .component-name {{ font-weight: 600; font-size: 15px; }}
  .badge {{ font-size: 10px; padding: 2px 8px; border-radius: 12px; font-weight: 600; text-transform: uppercase; }}
  .badge-model {{ background: #dbeafe; color: #1d4ed8; }}
  .badge-dataset {{ background: #dcfce7; color: #15803d; }}
  .badge-framework {{ background: #fef9c3; color: #854d0e; }}
  .badge-api-client {{ background: #fae8ff; color: #7e22ce; }}
  .component-meta {{ font-size: 12px; color: #666; display: flex; gap: 16px; flex-wrap: wrap; }}
  .risk-item {{ background: #fef2f2; border-left: 3px solid #dc2626; padding: 10px 14px; margin-top: 10px; border-radius: 0 4px 4px 0; font-size: 12px; }}
  .risk-item.medium {{ background: #fffbeb; border-color: #d97706; }}
  .risk-item.low {{ background: #f0fdf4; border-color: #16a34a; }}
  .risk-item .risk-title {{ font-weight: 600; margin-bottom: 4px; }}
  .data-egress {{ background: #fff7ed; border: 1px solid #fed7aa; padding: 10px 14px; border-radius: 4px; margin-top: 8px; font-size: 12px; }}
  .flag {{ display: inline-flex; align-items: center; gap: 4px; font-size: 11px; padding: 2px 8px; border-radius: 4px; margin-right: 6px; }}
  .flag-true {{ background: #fef2f2; color: #dc2626; }}
  .flag-false {{ background: #f0fdf4; color: #15803d; }}
  .footer {{ text-align: center; font-size: 11px; color: #999; margin-top: 20px; padding: 16px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>aibomstd Report</h1>
    <p>{subject_name} {subject_version} · Generated {generated} · aibomstd v{spec_version}</p>
  </div>

  <div class="summary">
    <div class="stat">
      <div class="label">Total Components</div>
      <div class="value">{total_components}</div>
    </div>
    <div class="stat">
      <div class="label">Risk Score</div>
      <div class="value risk-{risk_score}">{risk_score_upper}</div>
    </div>
    <div class="stat">
      <div class="label">Models</div>
      <div class="value">{count_model}</div>
    </div>
    <div class="stat">
      <div class="label">API Clients</div>
      <div class="value">{count_api}</div>
    </div>
    <div class="stat">
      <div class="label">Frameworks</div>
      <div class="value">{count_framework}</div>
    </div>
    <div class="stat">
      <div class="label">Data Egress</div>
      <div class="value">{data_leaves_flag}</div>
    </div>
  </div>

  {components_html}

  {compliance_html}

  <div class="footer">
    Generated by aibomstd · <a href="https://aibomstd.com">aibomstd.com</a> · Schema: {schema_url}
  </div>
</div>
</body>
</html>"""


def _risk_color(severity: str) -> str:
    return {
        "critical": "critical",
        "high": "high",
        "medium": "medium",
        "low": "low"
    }.get(severity, "low")


def _badge_class(component_type: str) -> str:
    return {
        "model": "badge-model",
        "dataset": "badge-dataset",
        "framework": "badge-framework",
        "api-client": "badge-api-client"
    }.get(component_type, "badge-framework")


def _render_component(component: dict) -> str:
    identity = component.get("identity", {})
    component_type = component.get("type", "unknown")
    service = component.get("service", {})
    risks = component.get("risks", [])
    license_info = component.get("license", {})

    meta_parts = []
    if identity.get("provider"):
        meta_parts.append(f"<span>Provider: {identity['provider']}</span>")
    if identity.get("version"):
        meta_parts.append(f"<span>Version: {identity['version']}</span>")
    if identity.get("source"):
        meta_parts.append(f"<span>Source: {identity['source']}</span>")
    if license_info.get("id"):
        meta_parts.append(f"<span>License: {license_info['id']}</span>")

    meta_html = '<div class="component-meta">' + "".join(meta_parts) + "</div>"

    service_html = ""
    if component_type == "api-client" and service:
        dlb = service.get("data-leaves-boundary", False)
        dr = service.get("data-residency", "unknown")
        endpoint = service.get("endpoint", "")
        models = ", ".join(service.get("models-used", []))
        service_html = f"""<div class="data-egress">
            <strong>External API Call</strong> · Endpoint: {endpoint}<br>
            Data leaves boundary: <strong>{'Yes' if dlb else 'No'}</strong> · Residency: <strong>{dr}</strong>
            {f'<br>Models used: {models}' if models else ''}
        </div>"""

    risks_html = ""
    for risk in risks:
        severity = risk.get("severity", "low")
        risks_html += f"""<div class="risk-item {severity}">
            <div class="risk-title">{risk.get('id', '')} · {risk.get('type', '').upper()} · {severity.upper()}</div>
            <div>{risk.get('description', '')}</div>
            {f"<div style='margin-top:4px;color:#555'><em>Recommendation: {risk['recommendation']}</em></div>" if risk.get('recommendation') else ''}
        </div>"""

    return f"""<div class="component">
        <div class="component-header">
            <span class="component-name">{identity.get('name', 'unknown')}</span>
            <span class="badge {_badge_class(component_type)}">{component_type}</span>
        </div>
        {meta_html}
        {service_html}
        {risks_html}
    </div>"""


def _render_compliance(compliance: dict) -> str:
    if not compliance:
        return ""

    eu = compliance.get("eu-ai-act", {})
    nist = compliance.get("nist-ai-rmf", {})

    eu_gaps = eu.get("gaps", [])
    nist_gaps = nist.get("gaps", [])

    if not eu_gaps and not nist_gaps:
        return ""

    eu_html = ""
    if eu_gaps:
        gaps_html = "".join(f"<li>{gap}</li>" for gap in eu_gaps)
        eu_html = f"""<div class="component">
            <div class="component-header">
                <span class="component-name">EU AI Act — Article 13</span>
                <span class="badge badge-model">Risk: {eu.get('risk-category', 'unknown').upper()}</span>
            </div>
            <div style="font-size:12px;color:#dc2626;margin-top:8px;font-weight:600">
                {len(eu_gaps)} compliance gap{'s' if len(eu_gaps) != 1 else ''} identified
            </div>
            <ul style="font-size:12px;color:#555;margin-top:6px;padding-left:20px">{gaps_html}</ul>
        </div>"""

    nist_html = ""
    if nist_gaps:
        gaps_html = "".join(f"<li>{gap}</li>" for gap in nist_gaps)
        nist_html = f"""<div class="component">
            <div class="component-header">
                <span class="component-name">NIST AI RMF</span>
            </div>
            <ul style="font-size:12px;color:#555;margin-top:6px;padding-left:20px">{gaps_html}</ul>
        </div>"""

    return f"""<div class="section">
        <div class="section-header">Compliance Gaps</div>
        {eu_html}
        {nist_html}
    </div>"""


def to_html(aibomstd_dict: dict) -> str:
    doc = aibomstd_dict.get("aibomstd", {})
    subject = doc.get("subject", {})
    summary = doc.get("summary", {})
    components = doc.get("components", [])
    compliance = doc.get("compliance", {})

    by_type = summary.get("by-type", {})
    risk_score = summary.get("risk-score", "none")
    data_leaves = summary.get("data-leaves-boundary", False)

    components_html = '<div class="section"><div class="section-header">AI Components</div>'
    for component in components:
        components_html += _render_component(component)
    components_html += "</div>"

    compliance_html = _render_compliance(compliance)

    return HTML_TEMPLATE.format(
        subject_name=subject.get("name", "Unknown"),
        subject_version=subject.get("version", ""),
        generated=doc.get("generated", datetime.now().isoformat()),
        spec_version=doc.get("specVersion", "0.1"),
        total_components=summary.get("total-components", 0),
        risk_score=risk_score,
        risk_score_upper=risk_score.upper(),
        count_model=by_type.get("model", 0),
        count_api=by_type.get("api-client", 0),
        count_framework=by_type.get("framework", 0),
        data_leaves_flag="YES" if data_leaves else "NO",
        components_html=components_html,
        compliance_html=compliance_html,
        schema_url=doc.get("schema", "https://aibomstd.com/schema/v0.1/aibomstd.schema.json")
    )
